<a href="https://colab.research.google.com/github/luizgpereira23-ops/Senai-Projects/blob/main/cadastro_clientes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Desafio da Aprendizagem
Desenvolver um programa estruturado que permita:

• Registrar vendas de produtos;

• Armazenar dados em variáveis e estruturas adequadas;

• Calcular totais, médias e identificar melhores resultados;

• Apresentar informações organizadas ao usuário;

• Garantir clareza, correção lógica e boa estrutura do código

## Funcionalidades mínimas:
### 1. Exiba um menu de opções, como:
o Cadastrar venda

o Exibir resumo das vendas

o Mostrar total faturado

o Identificar maior e menor venda

o Encerrar sistema

### 2. Solicite:
o Nome do produto

o Quantidade vendida

o Valor unitário

### 3. Armazene os dados em vetores.
### 4. Realize cálculos automáticos:
o Valor total por venda

o Faturamento total

o Média de vendas

### 5. Utilize estruturas de repetição para permitir múltiplos cadastros.
### 6. Utilize funções para organizar o código (ex.: cadastrarVenda(), calcularTotal(),
mostrarMenu()).

In [54]:
import pandas as pd
import sqlite3 as sql
import os

def cadastrar_venda(table_vendas:pd.DataFrame, is_cadastrar_venda:bool=True)->pd.DataFrame:

  produto = []
  quantidade = []
  valor_unitario = []

  while is_cadastrar_venda:
    # Inputs do usuário
    try:
      produto.append(input('Digite o nome do produto: '))
      quantidade.append(int(input('Digite a quantidade vendida: ')))
      valor_unitario.append(float(input('Digite o valor unitário (use . para decimais): ')))
    except Exception as e:
      print(f'Erro: {e}')
      continue

    # Cria nova linha para a tabela
    opcao = input('\nCadastrar nova venda? (s/n)')

    if opcao == 'n':
      is_cadastrar_venda = False

    new_rows = pd.DataFrame({'produto':produto,
                            'quantidade':quantidade,
                            'valor_unitario':valor_unitario})
  return new_rows

def criar_relatorio(table_vendas:pd.DataFrame):
  '''
  table_vendas: pd.DataFrame - Tabela de vendas
  - colunas: produto, quantidade, valor_unitario, valor_total

  Calcular:
  - Faturamento total
  - Média de vendas
  - Maior venda
  - Menor venda
  '''

  relatorio = pd.DataFrame(columns=['faturamento_total', 'media_vendas', 'maior_venda', 'menor_venda'])
  relatorio['faturamento_total'] = table_vendas['valor_total'].sum()
  relatorio['maior_venda'] = table_vendas['valor_total'].max()
  relatorio['menor_venda'] = table_vendas['valor_total'].min()
  relatorio['media_vendas'] = table_vendas['valor_total'].mean()

  return relatorio

def main():
  # Tabela para armazenar as vendas
  is_cadastrar_venda:bool = True

  if os.path.isfile('table_vendas.csv'):
    table_vendas = pd.read_csv('table_vendas.csv')
  else:
    table_vendas = pd.DataFrame(columns=['produto', 'quantidade', 'valor_unitario'])

  nova_linha = cadastrar_venda(table_vendas)
  table_vendas = pd.concat([table_vendas, nova_linha],axis=0, ignore_index=True)

  # Cálculo das métricas para relatório
  table_vendas['valor_total'] = table_vendas['quantidade'] * table_vendas['valor_unitario']

  print('\n======Tabela de vendas======')
  display(table_vendas)

  print('\n======Relatório======')
  display(criar_relatorio(table_vendas))

  #Salvar a tabela para histórico
  if os.path.isfile('table_vendas.csv'):
    pass
  else:
    table_vendas.to_csv('table_vendas.csv', index=False)

if __name__ == '__main__':
  main()

Digite o nome do produto: a
Digite a quantidade vendida: 1
Digite o valor unitário (use . para decimais): 1

Cadastrar nova venda? (s/n)n

======Tabela de vendas======

  produto  quantidade  valor_unitario  valor_total
0       a           1             2.0          2.0
1       b           1             1.0          1.0
2       a           1             1.0          1.0
3       b           1             1.0          1.0
4       1           1             1.0          1.0
5       a           1             1.0          1.0
6       a           1             1.0          1.0

8.0

======Relatório======

Empty DataFrame
Columns: [faturamento_total, media_vendas, maior_venda, menor_venda]
Index: []

# Testes

In [27]:
d = {'col1': [1, 2], 'col2': [3, 4]}
d[len(d)] = [5, 6]
d = pd.DataFrame(d)
d

   col1  col2  2
0     1     3  5
1     2     4  6

In [29]:
# Cria nova linha para a tabela
row = pd.DataFrame({'produto':'a',
                    'quantidade':1,
                    'valor_unitario':1,
                    'valor_total':1})

ValueError: If using all scalar values, you must pass an index